---
addons:
  apt:
    packages:
    - libsodium-dev
    - alex-3.1.7
    - happy-1.19.5
    - cabal-install-1.18
    - ghc-7.8.4
    sources:
    - sourceline: ppa:chris-lea/libsodium
    - hvr-ghc
after_script:
- rm -f $HOME/.cabal && ln -s $HOME/.cabal-tools $HOME/.cabal
- rm -f $HOME/.ghc && ln -s $HOME/.ghc-tools $HOME/.ghc
- hpc-coveralls hstox-0.0.1
branches:
  only:
  - master
cache:
  directories:
  - $HOME/.cabal-build
  - $HOME/.cabal-tools
  - $HOME/.ghc-build
  - $HOME/.ghc-tools
env: CABALVER=1.18 GHCVER=7.8.4
haskell:
  cabal: 1.18
  ghc: 7.8.4
  packages:
  - semdoc
install:
- export PATH=$HOME/.cabal/bin:/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:/opt/alex/3.1.7/bin:/opt/happy/1.19.5/bin:$PATH
- rm -rf $HOME/.cabal $HOME/.ghc
- mkdir -p $HOME/.cabal-tools $HOME/.ghc-tools
- rm -f $HOME/.cabal && ln -s $HOME/.cabal-tools $HOME/.cabal
- rm -f $HOME/.ghc && ln -s $HOME/.ghc-tools $HOME/.ghc
- cabal update
- mkdir -p $HOME/.cabal-build $HOME/.ghc-build
- rm -f $HOME/.cabal && ln -s $HOME/.cabal-build $HOME/.cabal
- rm -f $HOME/.ghc && ln -s $HOME/.ghc-build $HOME/.ghc
- cabal update
language: generic
package:
  name: hstox
  version: 0.0.1
script:
- rm -f $HOME/.cabal && ln -s $HOME/.cabal-tools $HOME/.cabal
- rm -f $HOME/.ghc && ln -s $HOME/.ghc-tools $HOME/.ghc
- cabal install hpc-coveralls stylish-haskell hlint aeson-0.9.0.1
- curl https://raw.githubusercontent.com/TokTok/toktok-stack/master/tools/stylish-haskell-lhs
  -o $HOME/.cabal/bin/stylish-haskell-lhs
- chmod +x $HOME/.cabal/bin/stylish-haskell-lhs
- hlint .
- stylish-haskell-lhs -i .
- git diff
- rm -f $HOME/.cabal && ln -s $HOME/.cabal-build $HOME/.cabal
- rm -f $HOME/.ghc && ln -s $HOME/.ghc-build $HOME/.ghc
- cabal install --enable-tests --enable-benchmarks --only-dependencies ./ semdoc
- if [ -n "semdoc" ]; then cabal install semdoc; fi
- cabal configure --enable-tests --enable-benchmarks --enable-library-coverage
- cabal test
- cabal check
- git checkout $TRAVIS_BRANCH
- semdoc src/tox/Network/Tox.lhs spec.old.md
- git checkout $TRAVIS_COMMIT
- semdoc src/tox/Network/Tox.lhs spec.new.md
- gem install gist
- diff spec.old.md spec.new.md > spec.md.diff || gist spec.md.diff
sudo: required
