language: haskell
ghc: 7.8

cache:
  directories:
    - $HOME/.cabal
    - $HOME/.ghc

install:
  - make configure
  - cabal install hpc-coveralls

script:
  - export LD_LIBRARY_PATH=$HOME/.cabal/extra-dist/lib
  - make check
  - tools/build-docs
  - git diff --exit-code

after_script:
  - hpc-coveralls hstox-0.0.1
